### ISSUE TITLE
Auto Update Ember Without Appstore review

### ISSUE THREAD

**Issue by hamzahio** [isleofcode/ember-cordova#270]
Good day,

I finished my app and i submitted to app store for now.

Every time i need fix small bug or style even add small js i have to submit it to app store.

So i found number of solution like this one [Cordova App Loader](https://github.com/markmarijnissen/cordova-app-loader) .
but this is not playing nice with ember ecosystem.

so is there any library or addon i can use it with ember.

if the answer is NO. who is willing to build with me this addon.

Thanks.

**Comment by alexblom** [comment]
This may or may not cause problems with App Store Rules. It's not something I've spent much time on personally, but I know both @christophersansone and @anulman have done something similar before. Both use the same handles on the ember-slack and are on the #e-cordova channel.

**Comment by christophersansone** [comment]
I am successfully using [cordova-hot-code-push](https://github.com/nordnet/cordova-hot-code-push) with Ember.  I wrapped the plugin's API within an Ember service, the app checks for updates on load, and I can force an update any time (e.g. a websocket update).  And it is all built into my continuous deployment process, so updates occur automatically when a new build is available.

I will say that it took a while to get it all working cleanly.  It seems straight-forward, until you are pulling your hair out because you just flashed a new version to your phone and are not seeing the latest changes.  If you choose to use this plugin, the best advice I can give is:

1. Remove the plugin during development and add it back during your deployment process.  This way, you don't have to worry it loading about an older version of the Ember app.  The plugin has an auto-reload service, but I prefer removing the plugin and just using ember-cordova's live reload.

2. If ever something about the hot code pushing does not work while you are building it out, try removing the plugin and adding it back.  Not sure why that matters, but knowing that would have saved me hours.

3. Uninstalling and reinstalling the app can also help a lot to ensure all old versions of the Ember app are gone.

Lastly, according to [the plugin's wiki](https://github.com/nordnet/cordova-hot-code-push/wiki), it is not inherently a violation of the App Store's terms of service, but follow their recommendations as to the frequency of updates and not notifying the users when a hot update occurs.

Hope this helps!

**Comment by hamzahio** [comment]
@alexblom thanks alex for your reply.

@christophersansone thanks for your time this help me alot. 👍

**Comment by christophersansone** [comment]
One more tip I'll mention (because it bit me again today).  Running `ember cdv:build` will build the Ember app and the Cordova app.  However, in between those two steps, you need to include the release info, usually generated by `cordova-hcp build`.  It must happen after the Ember app builds because the `www` folder is created fresh, but before the Cordova app builds so that the release information can be packaged into the app.

Currently I do this by basically calling the following:

```
ember cdv:build ... --skip-cordova-build
cordova-hcp build
ember cdv:build ... --skip-ember-build
```

@alexblom may have a better suggestion using hooks.

**Comment by tavosansal** [comment]
We have used https://microsoft.github.io/code-push/ ... pretty simple to setup.

**Comment by alexblom** [comment]
I'm going to close this now as it looks like we have a solution, and there are not plans to make it more first class to ember-cordova right now.
