### ISSUE TITLE
Complaining about missing IOS cordova path but only build platform is android.

### ISSUE THREAD

**Issue by v3ss0n** [isleofcode/ember-cordova#95]
I am building with ember cdv:build
but after update i got this error :

```
Built project successfully. Stored in "dist/".
Symlinked dist/ to cordova/www
 Using this version of Cordova with older version of cordova-ios is being deprecated. Consider upgrading to cordova-ios@4.0.0 or newer.
Error: The provided path "/home/v3ss/workspace/wavelocator/client/ember-cordova/cordova/platforms/ios" is not a Cordova iOS project.
```

i am building android

here is my env 

```
/* jshint node: true */

module.exports = function(environment) {
  var ENV = {
    modulePrefix: 'client',
    environment: environment,
    rootURL: '/',
    locationType: 'hash',
    EmberENV: {
      FEATURES: {
        // Here you can enable experimental features on an ember canary build
        // e.g. 'with-controller': true
      }
    },

    APP: {
      // Here you can pass flags/options to your application instance
      // when it is created
    },

    cordova: {
      rebuildOnChange: false,
      emulate: false,
      platform: 'android'
    }
  };

  if (environment === 'development') {
    // ENV.APP.LOG_RESOLVER = true;
    ENV.APP.LOG_ACTIVE_GENERATION = true;
    // ENV.APP.LOG_TRANSITIONS = true;
    // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
    ENV.APP.LOG_VIEW_LOOKUPS = true;
  }

  if (environment === 'test') {
    // Testem prefers this...
    ENV.baseURL = '/';
    ENV.locationType = 'none';

    // keep test console output quieter
    ENV.APP.LOG_ACTIVE_GENERATION = false;
    ENV.APP.LOG_VIEW_LOOKUPS = false;

    ENV.APP.rootElement = '#ember-testing';
  }

  if (environment === 'production') {

  }

  return ENV;
};
```

**Comment by v3ss0n** [comment]
my cordova version is 6.2.0

**Comment by v3ss0n** [comment]
now updated to ember-cordova 0.2.0 and i got this error:
ember-cordova: /home/v3ss/workspace/wavelocator/client/ember-cordova/cordova/platforms/ios/www/cordova_plugins.js did not exist. It is required for Device LiveReload to work.

**Comment by alexblom** [comment]
Just to be clear, you are running ember cdv:build --platform=android vs cdv:build without the flag?

Also, has this project recently been confirmed. Can you check for me if the cordova/platforms/android directory exists and generally has what you would expect?

**Comment by optikalefx** [comment]
Downgrading for now, but as of 0.2.0 also getting the cordova_plugins.js error that @v3ss0n mentioned

**Comment by alexblom** [comment]
Following up, I can only replicate this when the platform I am building for does not exist. Please let me know if this works, and then I can clear up the documentation / handling of env defaults.

The default for any build/serve command is iOS, so unless you pass Android as a platform it will build for iOS (e.g. `ember cdv:build` builds for iOS vs `ember:cdv:build --platform=android`).

The error you are seeing happens when you try to run a cordova command (e.g. build, serve) and the platform target has not yet been added to cordova. This is not yet automated in ember-cordova, but I hope to make it so soon. Presumably you have installed Android as a platform, but the android default is not being respected.

So can you please:
1) Confirm ember-cordova/cordova/platforms/android exists. If not, run `ember cdv platform add android`;
2) Confirm you are building for Android: `ember cdv:build --platform=android`.

**Comment by v3ss0n** [comment]
`ember:cdv build --platform=android` works.
But then plugins for geolocation no longer working 
i will test without ember and with ember and let you know.

**Comment by v3ss0n** [comment]
> Android as a platform, but the android default is not being respected.
yes thats the problem.

**Comment by alexblom** [comment]
If you update to the newest version, I've ensured & tested defaults.
